// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: projects.sql

package database

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, created_at, updated_at, title, description)
VALUES (
	gen_random_uuid(), 
	NOW(), 
	NOW(), 
	$1, 
	$2
)
RETURNING id, created_at, updated_at, title, description
`

type CreateProjectParams struct {
	Title       string
	Description sql.NullString
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Title, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Description,
	)
	return i, err
}
